     tasks:
       - init: sudo apt-get update && sudo apt-get install -y qt5-default
         command: |
           mkdir build
           cd build
           qmake ..
           make
     ports:
       - port: 6080
         onOpen: open-preview
     


