tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools cmake xvfb adb
    command: |
      mkdir build
      cd build
      cmake ..
      make
ports:
  - port: 6080
    onOpen: open-preview
